# Reproducible C++ runtime; weights remain separate, user-selected downloads.
include(FetchContent)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(LLAMA_BUILD_COMMON OFF CACHE BOOL "" FORCE)
set(LLAMA_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(LLAMA_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(LLAMA_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(LLAMA_BUILD_SERVER OFF CACHE BOOL "" FORCE)
set(LLAMA_CURL OFF CACHE BOOL "" FORCE)
set(LLAMA_BUILD_IS_DEV OFF CACHE BOOL "" FORCE)
set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
set(GGML_CUDA OFF CACHE BOOL "" FORCE)
set(GGML_VULKAN OFF CACHE BOOL "" FORCE)
set(GGML_METAL OFF CACHE BOOL "" FORCE)
set(GGML_BLAS OFF CACHE BOOL "" FORCE)
set(GGML_AVX512 OFF CACHE BOOL "" FORCE)
FetchContent_Declare(llama
    URL https://codeload.github.com/ggml-org/llama.cpp/tar.gz/d2e54583c7452353eb35d40431281f6ee984332f
    URL_HASH SHA256=8aeb94872f97ddc9c80bca3824d95aba00bdb17d1d28813db22150fb6caf6d15
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(llama)
if(MINGW)
    target_compile_options(ggml-cpu PRIVATE "-include" "${CMAKE_CURRENT_LIST_DIR}/../vendor/llama/WindowsThreadPower.h")
endif()
configure_file("${llama_SOURCE_DIR}/LICENSE" "${CMAKE_BINARY_DIR}/llama-MIT.txt" COPYONLY)
foreach(notice vendor/hash/xxhash/LICENSE vendor/hash/sha256/LICENSE vendor/hash/rotate-bits/LICENSE.md)
    string(REPLACE "/" "-" name "${notice}")
    configure_file("${llama_SOURCE_DIR}/${notice}" "${CMAKE_BINARY_DIR}/llama-notices/${name}" COPYONLY)
endforeach()
# These components carry their license notice in the source header.
foreach(source ggml/src/ggml-cpu/llamafile/sgemm.cpp vendor/hash/sha1/sha1.c)
    file(STRINGS "${llama_SOURCE_DIR}/${source}" notice LIMIT_COUNT 22)
    string(REPLACE ";" "\n" notice "${notice}")
    string(REPLACE "/" "-" name "${source}")
    file(WRITE "${CMAKE_BINARY_DIR}/llama-notices/${name}.txt" "${notice}\n")
endforeach()
